### ISSUE TITLE
Add support for `POST` method

### ISSUE THREAD

**Issue by es-que** [prometheus-community/json_exporter#69]
Can we add support to POST data to the remote endpoint.

**Comment by JosephWoodward** [comment]
It looks like this can be closed now?

**Comment by paulfantom** [comment]
> It looks like this can be closed now?

I don't think so. It looks like the exporter is always doing GET - https://github.com/prometheus-community/json_exporter/blob/28dde07d5159f116a1f847b28154c5c097ca1f67/exporter/util.go#L120

**Comment by rustycl0ck** [comment]
> It looks like this can be closed now?

No, because that patch was on a different fork (although it addresses the same issue). I didn't send it upstream because I wasn't sure if this would really be useful to anyone, as well as that it might make it more complex for some people to use this feature.

In any case, if you think you need this feature, please leave a "thumbs up" reaction on the issue and I can take a look at sending a pull request to fix this.

**Comment by JosephWoodward** [comment]
> No, because that patch was on a different fork (although it addresses the same issue).

Ah okay, my misunderstanding 👍

**Comment by karabanov** [comment]
Please add support to POST data to the remote endpoint.

**Comment by adean-consensys** [comment]
Replying to this as it would be a _really_ nice feature add 👍
